# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./temp/example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/cf4eddcc-e8cd-46fc-bcc6-9937668ab30d/transcription
Content-Type: application/json

{
  "prompt": "storybook, react, front-end"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/completion
Content-Type: application/json

{
  "videoId": "cf4eddcc-e8cd-46fc-bcc6-9937668ab30d",
  "temperature": 0.5,
  "prompt": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}